import { Position, MarkerType } from '@xyflow/react';

interface InternalPosition {
  x: number;
  y: number;
}

interface Measured {
  width: number;
  height: number;
}

// Use this type in edge helper functions that expect measured properties
export interface EnhancedNode {
  x: number;
  y: number;
  measured: Measured;
  internals: { positionAbsolute: InternalPosition };
}

function getNodeIntersection(
  intersectionNode: EnhancedNode,
  targetNode: EnhancedNode
): { x: number; y: number } {
  const { width: intersectionNodeWidth, height: intersectionNodeHeight } =
    intersectionNode.measured;
  const intersectionNodePosition = intersectionNode.internals.positionAbsolute;
  const targetPosition = targetNode.internals.positionAbsolute;

  const w = intersectionNodeWidth / 2;
  const h = intersectionNodeHeight / 2;

  const x2 = intersectionNodePosition.x + w;
  const y2 = intersectionNodePosition.y + h;
  const x1 = targetPosition.x + targetNode.measured.width / 2;
  const y1 = targetPosition.y + targetNode.measured.height / 2;

  const xx1 = (x1 - x2) / (2 * w) - (y1 - y2) / (2 * h);
  const yy1 = (x1 - x2) / (2 * w) + (y1 - y2) / (2 * h);
  const a = 1 / (Math.abs(xx1) + Math.abs(yy1));
  const xx3 = a * xx1;
  const yy3 = a * yy1;
  const x = w * (xx3 + yy3) + x2;
  const y = h * (-xx3 + yy3) + y2;

  return { x, y };
}

function getEdgePosition(
  node: EnhancedNode,
  intersectionPoint: { x: number; y: number }
): Position {
  const n = { ...node.internals.positionAbsolute, ...node };
  const nx = Math.round(n.x);
  const ny = Math.round(n.y);
  const px = Math.round(intersectionPoint.x);
  const py = Math.round(intersectionPoint.y);

  if (px <= nx + 1) {
    return Position.Left;
  }
  if (px >= nx + n.measured.width - 1) {
    return Position.Right;
  }
  if (py <= ny + 1) {
    return Position.Top;
  }
  if (py >= n.y + n.measured.height - 1) {
    return Position.Bottom;
  }

  return Position.Top;
}

export function getEdgeParams(
  source: EnhancedNode,
  target: EnhancedNode
): {
  sx: number;
  sy: number;
  tx: number;
  ty: number;
  sourcePos: Position;
  targetPos: Position;
} {
  const sourceIntersectionPoint = getNodeIntersection(source, target);
  const targetIntersectionPoint = getNodeIntersection(target, source);

  const sourcePos = getEdgePosition(source, sourceIntersectionPoint);
  const targetPos = getEdgePosition(target, targetIntersectionPoint);

  return {
    sx: sourceIntersectionPoint.x,
    sy: sourceIntersectionPoint.y,
    tx: targetIntersectionPoint.x,
    ty: targetIntersectionPoint.y,
    sourcePos,
    targetPos,
  };
}

// Types for nodes and edges generated by the helper function below.
export interface FlowNode {
  id: string;
  data: { label: string };
  position: { x: number; y: number };
}

export interface FlowEdge {
  id: string;
  source: string;
  target: string;
  type: string;
  markerEnd: {
    type: MarkerType;
  };
}

export function initialElements(
  data: Record<string, unknown>,
  options: {
    centerX?: number;
    centerY?: number;
    radius?: number;
    nodePrefix?: string;
  } = {}
): { nodes: FlowNode[]; edges: FlowEdge[] } {
  const nodes: FlowNode[] = [];
  const edges: FlowEdge[] = [];
  const {
    centerX = window.innerWidth / 2,
    centerY = window.innerHeight / 2,
    radius = 250,
    nodePrefix = 'node',
  } = options;

  let nodeCounter = 0;

  // Helper function to process the JSON structure
  function processJSON(obj: unknown, parentId: string | null = null): void {
    const entries: [string, unknown][] = Array.isArray(obj)
      ? obj.map((item, index) => [String(index), item])
      : Object.entries(obj as Record<string, unknown>);

    entries.forEach(([key, value]) => {
      if (Array.isArray(value) && value.length === 0) {
        return;
      }

      const currentId = `${nodePrefix}-${nodeCounter++}`;

      // Provide a default position here
      nodes.push({
        id: currentId,
        data: { label: Array.isArray(obj) ? String(key) : key },
        position: { x: 0, y: 0 },
      });

      // Add edge from current node to its parent, if applicable
      if (parentId !== null) {
        edges.push({
          id: `edge-${parentId}-${currentId}`,
          source: currentId,
          target: parentId,
          type: 'floating',
          markerEnd: {
            type: MarkerType.Arrow,
          },
        });
      }

      // Recursively process children if value is a non-null object (but not an array)
      if (value !== null && typeof value === 'object' && !Array.isArray(value)) {
        processJSON(value, currentId);
      }
    });
  }

  // Create root node
  const rootKey = Object.keys(data)[0];
  const rootId = 'target';
  nodes.push({
    id: rootId,
    data: { label: rootKey! },
    position: { x: centerX, y: centerY },
  });

  // Process the rest of the structure
  processJSON(data[rootKey!], rootId);

  // Position remaining nodes in a circle around the root node
  const nonRootNodes = nodes.filter((node) => node.id !== rootId);
  nonRootNodes.forEach((node, index) => {
    const degrees = index * (360 / nonRootNodes.length);
    const radians = (degrees * Math.PI) / 180;
    const x = radius * Math.cos(radians) + centerX;
    const y = radius * Math.sin(radians) + centerY;
    node.position = { x, y };
  });

  return { nodes, edges };
}