import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import { SidebarProvider, SidebarTrigger } from "~/components/ui/sidebar";
import { AppSidebar } from "~/components/app-sidebar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable} dark antialiased`}>
      <body>
        <TRPCReactProvider>
          <SidebarProvider defaultOpen>
            <AppSidebar />
              <SidebarTrigger className="p-4 m-2"/>
              <div className="flex min-h-screen flex-col items-center justify-center bg-background w-full bg-opacity-[0.98] text-neutral-100 p-4">
              {children}
              </div>
          </SidebarProvider>

        </TRPCReactProvider>
      </body>
    </html>
  );
}
